### ISSUE TITLE
Formatting/style issue

### ISSUE THREAD

**Issue by MrGallo** [tlui2/pbd-solutions#1]
https://github.com/tlui2/pbd-solutions/blob/8249169eca376bd29a0ba27144a468c0254373f5/pbd-solutions/08/numbersandmath.java#L17-L20

1. Remove whitespace padding from inside brackets.
2. Move the **closing** curly-brace on line 18 to line 19

```java
 		System.out.println("Is it greater or equal? " + ( 5 >= -2 )); 
 		System.out.println("Is it less or equal? " + ( 5 <= -2 ));   
        } 
 } 
```

**Comment by tlui2** [comment]
Okay Ill fix my styling in future assignments!
